### ISSUE TITLE
inlining external content

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#32] opened 2015-08-10 14:28 UTC
In the documentation, when the "Imports" section refers to "HTML Imports", do you mean elements of the form `<link rel="import" href="external.html">`? If so, such elements are restricted (in conforming HTML documents) to the document's `<head>` element, which is not where you want to inline the content of an external document.

Given that "HTML Imports are treated specially in an ecmarkup document", maybe ecmarkup should instead have a custom element for the purpose, e.g. `<emu-include>` or `<emu-inline>`.

**Comment by domenic** [comment] 2015-08-10 15:36
Dupe of #25.

**Comment by bterlson** [comment] 2015-08-10 16:29
I don't buy the "link goes in head" argument since UAs handle links in body in an interoperable and obvious way as far as I can tell. Spec simply doesn't reflect reality :-P

But that said, after Domenic took me to task in #25, I have come around to the idea even though it's more painful to write for authors. It also turns out that having all import content nested under an element makes partial builds much easier - which is something I will almost certainly be implementing once any major work happens on the full HTML doc.

**Comment by jmdyck** [comment] 2015-08-10 19:24
oops, sorry for the dupe.

**Comment by domenic** [comment] 2015-08-11 00:34
> I don't buy the "link goes in head" argument since UAs handle links in body in an interoperable and obvious way as far as I can tell. Spec simply doesn't reflect reality :-P

It's an authoring conformance criterion. The same as how `<b><i>foo</b></i>` is invalid HTML, even though all browsers or other parsers handle it correctly.

**Closed** 2015-08-13 23:52 UTC
Labels: enhancement
