### ISSUE TITLE
Blank line leads to blank section

### ISSUE THREAD

**Issue by littledan** [bterlson/ecmarkup#39] opened 2015-08-26 00:03 UTC
Let's continue the discussion from https://github.com/domenic/ecmarkdown/issues/38

```
<emu-clause>
<h1>Foobar</h1>

Baz
</emu-clause>
```

The result has an empty body and just a heading.

**Comment by littledan** [comment] 2015-08-26 00:04
And this was done with ecmarkup v2.0.3

**Comment by bterlson** [comment] 2015-08-27 21:12
I guess this is a dupe of #40 actually.

**Comment by domenic** [comment] 2015-08-27 21:18
Is it? What I got from this bug report was that the text "Baz" actually disappeared. Which seems bad.

**Comment by littledan** [comment] 2015-08-27 21:21
Yeah this is a different bug

**Comment by bterlson** [comment] 2015-08-27 22:41
Oh, sorry! I misread the issue :(

**Comment by bterlson** [comment] 2015-08-27 23:53
Tracked it down, made multiple fixes to EMD in this area: https://github.com/domenic/ecmarkdown/pull/39.

**Comment by bterlson** [comment] 2015-09-02 21:25
This is fixed in the latest EMD!

**Closed by bterlson** 2015-09-02 21:25 UTC
